// Generated by Lasy AI - https://lasy.ai
import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Curlara - Cuidados Personalizados para Cabelos Cacheados",
  description: "Análise com IA, rotinas personalizadas e produtos sob medida para seus cachos",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Curlara",
  },
  icons: {
    icon: "https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/e1451ac7-4bbf-4b7e-af1f-e8bf3d88dd8f.png",
    apple: "https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/e1451ac7-4bbf-4b7e-af1f-e8bf3d88dd8f.png",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  themeColor: "#10b981",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <link rel="apple-touch-icon" href="https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/e1451ac7-4bbf-4b7e-af1f-e8bf3d88dd8f.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased touch-manipulation`}
      >
        {children}
      </body>
    </html>
  );
}
